#postgres server is visible as pgsql-server in pgadmin panel

version: '3'
services:

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: "fib"
      POSTGRES_PASSWORD: "fib"
      POSTGRES_DB: "fib"
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 123@test.pl
      PGADMIN_DEFAULT_PASSWORD: '123'
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "8090:80"
    restart: unless-stopped
    links:
      - "postgres:pgsql-server"

volumes:
    postgres:
    pgadmin: